language: ruby
deploy:
  provider: heroku
  api_key:
    secure: CBA3cgeyLSLm+yccOWodozR6sMTuQoV4o7/F736auvqrrgJxFyQ3CyT0jC97SiNkEDRV3ewjA/GOxdMoKgo7bZUJgliT/xdzJ+WFQ64F+7rRf11z2iJT8xOGb5DJpvmok4Ve6Wcjy/vhuXpSVBJ1O7bsMZB41Y+YtR+b9YnWAl0=
  app: capra
  on:
    #repo: thisiscapra/Capra
    branch: new-site
